#include "init.h"
#include "tetromino.h"

TrnRGBColor TRN_ALL_TETROMINO_COLORS[TRN_NUMBER_OF_TETRONINO];

void trn_init()
{
    TRN_ALL_TETROMINO_COLORS[TRN_TETROMINO_I] = TRN_CYAN;
    TRN_ALL_TETROMINO_COLORS[TRN_TETROMINO_O] = TRN_YELLOW;
    TRN_ALL_TETROMINO_COLORS[TRN_TETROMINO_T] = TRN_PURPLE;
    TRN_ALL_TETROMINO_COLORS[TRN_TETROMINO_S] = TRN_GREEN;
    TRN_ALL_TETROMINO_COLORS[TRN_TETROMINO_Z] = TRN_RED;
    TRN_ALL_TETROMINO_COLORS[TRN_TETROMINO_J] = TRN_BLUE;
    TRN_ALL_TETROMINO_COLORS[TRN_TETROMINO_L] = TRN_ORANGE;
}

