#ifndef TRN_TRN_TETROMINO_SRS_H
#define TRN_TRN_TETROMINO_SRS_H

#include "tetromino.h"

enum TrnTetrominoTypeSRS {TRN_TETROMINO_SRS_I, TRN_TETROMINO_SRS_O, TRN_TETROMINO_SRS_T, TRN_TETROMINO_SRS_S, TRN_TETROMINO_SRS_Z, TRN_TETROMINO_SRS_J, TRN_TETROMINO_SRS_L};

TrnTetrominosCollection* getTetrominosCollectionSRS();

#endif
